### ISSUE TITLE
7.3.5 db2, bad handling of editions

### ISSUE THREAD

**Issue by Leschen** [WowDevTools/WDBXEditor#48] opened 2018-02-27 23:16 UTC
So I tried lot's of configuration, brut editing in the software, CSV importing, SQL importing.
TextureFileData is not saved well, it fucks up in game.
ModelFileData too.
Both are saved well at first glance but in game it's fucked up.

Itemdisplayinfo too. CSV, SQL not saved + can't brut edit it since the software is crashing upon scrolling and going to the cell. Can't even save the new value that I wrote. Software just stop working and i can't even quit it the normal way.

CreatureDisplayInfo too, hotfix table works but not the wdbx edit, CSV + SQL, can't even open it anymore after saving the changes.

Some other errors like CharSections.db2, in CSV format sometimes I got an error when importing the csv. Datatype problem whereas with SQL import there's no problem.

Hope it helps you !

**Comment by barncastle** [comment] 2018-03-05 12:08
For anyone that is experiencing the same problems:

Having looked into this, the issues are mainly around valid values. With the onset of WDC1, uncommon bit sized integers are now common place, even on IDs. An example of this is the ID column on TextureFileData is now an int22 opposed to an int32. The data being imported began at a value that overflowed this and hence resulted in breaking changes in game. I've now added validation to every data entry point in the program to counteract this.

The CSV DataType problem is, again, invalid values. This is usually a localised notation that is not factored for or an invalid/missing value in the dataset. Anything like this I'd need to see the CSV file.

The soft locking was caused by the cell bitwidth validation which is now fixed in the dev build.

---

@Leschen The other issues I'm still yet to investigate. If you could keep maintaining issues on here that'd be grand, I'll poke you on Discord when I get a chance.

**Comment by barncastle** [comment] 2018-03-07 12:16
Closing this, replicated in #51. Will look tonight if I get a chance.

**Closed by barncastle** 2018-03-07 12:16 UTC
